#!/usr/bin/env bash
if [ "$1x" = "-sx" ]; then
  source=1
  env=$2
else
  source=
  env=$1
fi
env=/nix/var/nix/profiles/per-user/$USER/envs/$env
if [ -f $env/etc/env-support ]; then
  . $env/etc/env-support
fi
export PATH=$env/bin:$env/sbin:$PATH
export EMACSLOADPATH=$env/share/emacs/site-lisp:$EMACSLOADPATH
export ACTIVE_NIX_ENV=$env
export XDG_DATA_DIRS=$env/share:$XDG_DATA_DIRS
export PKG_CONFIG_PATH=$env/lib/pkgconfig:$PKG_CONFIG_PATH
export ACLOCAL_PATH=$env/share/aclocal
export LIBRARY_PATH=$env/lib
if [ -z "$source" ]; then
  exec -a bash
fi
